name: Continuous Deployment to GCP Cloud Function

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Enable manual triggering
  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy Cloud Function
      run: |
        gcloud functions deploy fake-shop-etl \
        --runtime python39 \
        --trigger-resource fake-shop-lake \
        --trigger-event google.storage.object.finalize \
        --entry-point=process_file \
        --region=us-central1

