name: Cloud Function CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Enable manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCP_CI_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: false  # Disable default credentials export

      - name: Set up GCP service account credentials
        run: |
          mkdir ./.gcloud
          echo "$KEYFILE" > ./.gcloud/service-account.json
        shell: bash
        env:
          KEYFILE: ${{ secrets.GCP_CI_SA_KEY }}

      - name: Run tests
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./.gcloud/service-account.json
        run: |
          # Install the required dependencies
          pip install -r requirements.txt

          # Run your tests here
          python main.py
